In [ ]:
# Written by Jayden
import pandas as pd
import numpy as np
import re
import xgboost as xg
import time
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from pathlib import Path

In [2]:
from fractions import Fraction

def fraction_to_decimal(fraction_str):
  """Converts a fraction string to its decimal representation."""
  try:
    return float(Fraction(fraction_str))
  except ValueError:
    return "Invalid fraction format"
  except ZeroDivisionError:
      return "Cannot divide by zero"

In [3]:
file_path = Path("../output/bach_chord_int_data.csv")

try:
    df = pd.read_csv(file_path)
except FileNotFoundError:
    print(f"Error: File not found at {file_path}")

df['duration'] = df['duration'].apply(Fraction)
df['duration'] = df['duration'].astype(float)

display(df.head())

,lookback_1,lookback_2,lookback_3,lookback_4,lookback_5,label,duration,file,position
0,0,0,0,0,0,17,0.500000,"Bach, Johann Sebastian, Partita in B-flat majo...",0
1,0,0,0,0,17,17,0.333333,"Bach, Johann Sebastian, Partita in B-flat majo...",1
2,0,0,0,17,17,17,0.250000,"Bach, Johann Sebastian, Partita in B-flat majo...",2
3,0,0,17,17,17,21,0.250000,"Bach, Johann Sebastian, Partita in B-flat majo...",3
4,0,17,17,17,21,17,0.083333,"Bach, Johann Sebastian, Partita in B-flat majo...",4

In [4]:
X_label = df.drop(columns = ['label', 'duration', 'position', 'file'])
y_label = df['label']

X_duration = df.drop(columns = ['duration', 'position', 'file'])
y_duration = df['duration']

display(X_label.head())
display(y_label.head())
display(X_duration.head())
display(y_duration.head())

X_label_train, X_label_val, y_label_train, y_label_val = train_test_split(X_label, y_label, test_size=0.2, random_state=1)
X_duration_train, X_duration_val, y_duration_train, y_duration_val = train_test_split(X_duration, y_duration, test_size=0.2, random_state=1)

   lookback_1  lookback_2  lookback_3  lookback_4  lookback_5
0           0           0           0           0           0
1           0           0           0           0          17
2           0           0           0          17          17
3           0           0          17          17          17
4           0          17          17          17          21

0    17
1    17
2    17
3    21
4    17
Name: label, dtype: int64

   lookback_1  lookback_2  lookback_3  lookback_4  lookback_5  label
0           0           0           0           0           0     17
1           0           0           0           0          17     17
2           0           0           0          17          17     17
3           0           0          17          17          17     21
4           0          17          17          17          21     17

0    0.500000
1    0.333333
2    0.250000
3    0.250000
4    0.083333
Name: duration, dtype: float64

In [5]:
print(y_label.max())

3878

In [6]:
le_label = LabelEncoder()
le_duration = LabelEncoder()

xgb_label_model = xg.XGBClassifier()
xgb_duration_model = xg.XGBClassifier()

In [7]:
'''X_label_train = X_label_train[0:10000]
y_label_train = y_label_train[0:10000]
X_duration_train = X_duration_train[0:50000]
y_duration_train = y_duration_train[0:50000]'''

y_label_train = le_label.fit_transform(y_label_train)
y_duration_train = le_duration.fit_transform(y_duration_train)

In [13]:
#start_time = time.perf_counter()
xgb_label_model.fit(X_label_train, y_label_train)
elapsed_time = time.perf_counter() - start_time
#print(f"Time taken to train label model: {elapsed_time}")

#start_time = time.perf_counter()
xgb_duration_model.fit(X_duration_train, y_duration_train)
elapsed_time = time.perf_counter() - start_time
#print(f"Time taken to train duration model: {elapsed_time}")

In [9]:
y_label_preds = xgb_label_model.predict(X_label_val)
y_label_preds = le_label.inverse_transform(y_label_preds)

In [10]:
accuracy_label = accuracy_score(y_label_val, y_label_preds)
#print(f"Validation Accuracy(label): {accuracy_label}")

In [11]:
lookback1 = 0
lookback2 = 0
lookback3 = 0
lookback4 = 0
lookback5 = 0
position = 0
duration = 0.5

label_data = {'lookback_1' : [lookback1],
              'lookback_2' : [lookback2],
              'lookback_3' : [lookback3],
              'lookback_4' : [lookback4],
              'lookback_5' : [lookback5]}
label_df = pd.DataFrame(label_data)
#print(label_df)

duration_data = {'lookback_1' : [lookback1],
                 'lookback_2' : [lookback2],
                 'lookback_3' : [lookback3],
                 'lookback_4' : [lookback4],
                 'lookback_5' : [lookback5],
                 'label' : [duration]}
duration_df = pd.DataFrame(duration_data)
#print(duration_df)

print("chord, duration")
for i in range(128):
    #label_prediction = xgb_label_model.predict(label_df)
    #label_prediction = le_label.inverse_transform(label_prediction)
    label_probabilities = xgb_label_model.predict_proba(label_df)
    label_prediction = np.array([np.random.choice(xgb_label_model.classes_, p=label_probabilities[0])])
    label_prediction = le_label.inverse_transform(label_prediction)

    for x in range(2, 6):
        label_df[f'lookback_{x-1}'] = label_df[f'lookback_{x}']
    label_df['lookback_5'] = label_prediction
    duration_df['label'] = label_prediction
    #print(label_df)

    duration_prediction = xgb_duration_model.predict(duration_df)
    duration_prediction = le_duration.inverse_transform(duration_prediction)
    #print(duration_df)
    print(f"{label_prediction[0]}, {Fraction(duration_prediction[0]).limit_denominator(12)}")

    for x in range(2, 6):
        duration_df[f'lookback_{x-1}'] = duration_df[f'lookback_{x}']
    duration_df['lookback_5'] = label_prediction

chord, duration
16, 1/4
36, 1/2
36, 1/4
512, 1/4
661, 1/6
144, 1/4
128, 1/12
144, 1/4
128, 1/12
662, 1/12
528, 1/6
516, 1/4
2305, 1/4
5, 1/4
4, 1/4
2324, 1/4
769, 1/4
773, 1/6
2194, 1/4
2176, 1/6
2368, 1/4
2368, 1/12
160, 1/4
32, 1/4
1, 1/4
1, 1/12
2176, 1/4
2176, 1/12
1409, 1/4
1, 1/4
2133, 1/4
145, 1/4
1669, 1/4
656, 1/12
1, 1/6
1, 1/4
513, 1/4
1153, 1/4
16, 1/4
128, 1/4
128, 1/4
132, 1/4
4, 1/4
20, 1/4
5, 1/4
17, 1/4
128, 1/4
49, 1/4
512, 1/4
129, 1/4
161, 1/4
128, 1/4
128, 1/4
128, 1/4
2052, 1/4
2048, 1/12
576, 1/4
1, 1/4
2065, 1/4
512, 1/4
2052, 1/4
2560, 1/4
17, 1/4
21, 1/4
4, 1/6
517, 1/4
513, 1/4
1152, 1/4
544, 1/4
32, 1/4
1060, 1/4
544, 1/4
548, 1/4
516, 1/4
580, 1/4
2084, 1/4
2229, 1/12
128, 1/12
146, 1/4
129, 1/4
4, 1/4
1, 1/12
1, 1/12
1, 1/12
5, 1/4
17, 1/6
1, 1/4
1, 1/4
1, 1/12
1, 1/12
1, 1/12
21, 1/4
516, 1/4
516, 1/4
4, 1/4
5, 1/4
5, 1/12
2324, 1/4
2561, 1/6
2560, 1/4
512, 1/12
1, 1/12
789, 1/4
1, 1/12
1, 1/4
69, 1/4
64, 1/12
2113, 1/12
2049, 1/6
129, 1/4
85, 1/4
129, 1/4
4, 1/4
1, 1/4
1, 1/12
128, 1/4
192, 1/12
192, 1/12
4, 1/4
5, 1/4
1, 1/12
1, 1/4
2561, 1/4
2560, 1/6
513, 1/4
1, 1/4
17, 1/3
1, 1/12

In [12]:
print(label_df)
print(duration_df)

   lookback_1  lookback_2  lookback_3  lookback_4  lookback_5
0         129         132         130          16         128
   lookback_1  lookback_2  lookback_3  lookback_4  lookback_5  label
0         129         132         130          16         128    128

In [12]:
print(label_probabilities)

[[1.32850423e-01 1.01674600e-02 9.54825506e-02 1.21863550e-02
  2.15476641e-04 6.60479942e-04 1.61573043e-04 1.03316837e-04
  1.32309055e-04 2.85082951e-05 8.04890238e-04 1.46733103e-02
  3.75315649e-05 1.40206364e-03 1.05262222e-02 4.32657339e-02
  1.58241135e-03 1.23136991e-03 1.30486358e-02 3.10266973e-03
  2.13951641e-03 1.74512446e-04 4.63933211e-05 6.44662753e-02
  2.28824746e-03 1.35087234e-03 3.94175714e-03 4.06992367e-05
  6.12403499e-04 3.73524032e-04 1.27202962e-04 7.53643631e-04
  9.68860986e-04 2.09270991e-04 6.15367957e-04 3.39961494e-04
  4.05592262e-04 1.34543376e-03 1.02310069e-03 7.25993365e-02
  3.24389315e-04 1.27755443e-03 1.07034597e-04 2.60515744e-03
  3.90709320e-04 2.97494320e-04 4.36236587e-05 9.51553229e-03
  1.21295813e-03 2.48102471e-04 5.00470014e-05 1.79052222e-04
  6.54987351e-04 7.92242703e-04 2.04825905e-04 6.56102737e-03
  7.00672914e-04 1.40784250e-04 4.73038584e-04 1.11474493e-03
  4.15246846e-04 3.16434586e-03 6.12227741e-05 1.51516042e-05
  4.94371961e-05 3.54558765e-03 1.69267356e-02 6.69345973e-05
  6.91943351e-05 4.59796371e-04 3.22785549e-04 2.12195955e-05
  7.04978360e-04 2.93046935e-04 6.35681557e-04 6.91581564e-03
  5.37867134e-04 1.40797012e-04 8.57146922e-04 1.55117072e-04
  1.25931649e-04 3.80475452e-04 4.68240796e-05 1.82880409e-04
  2.06213677e-04 6.32587908e-05 2.13136213e-04 2.29386478e-05
  2.95443082e-04 1.54695299e-04 5.79101907e-04 4.19538628e-05
  1.70816988e-04 1.92090971e-04 3.94759380e-04 1.34340473e-04
  8.66607079e-05 8.80010333e-03 2.91682809e-04 5.09756464e-05
  1.79612587e-04 1.64767087e-03 1.31790410e-04 6.77770004e-05
  1.19863573e-04 2.31355170e-05 1.45012327e-03 8.96246493e-05
  3.66302161e-03 7.13969639e-05 1.23656311e-04 1.76539223e-04
  4.86474237e-05 4.54615540e-04 3.13723926e-04 4.97929461e-04
  1.59867486e-05 1.33418897e-03 1.07177964e-03 4.83765936e-04
  1.55938469e-04 3.13139390e-05 7.28293817e-05 1.13694659e-04
  6.10487419e-04 3.36933590e-05 1.62446449e-04 2.63064075e-03
  1.71774777e-03 9.08696733e-04 6.21927087e-04 6.67062413e-04
  1.02162980e-04 2.78633088e-04 8.33287090e-03 3.12950433e-04
  1.16977113e-04 1.95550194e-04 2.23149895e-04 6.22592575e-04
  5.03651623e-04 1.00998222e-04 1.10715271e-04 5.69382333e-04
  6.05066831e-04 2.39821020e-04 8.80241932e-05 1.18522265e-04
  1.01017773e-04 4.82512696e-04 1.24760234e-04 1.08296284e-04
  5.75186918e-03 2.15565015e-04 1.10799243e-04 1.62964559e-03
  3.49268608e-04 2.27271685e-05 8.25028183e-05 1.73301160e-05
  5.57519787e-04 1.02022488e-03 4.30598331e-04 1.34728886e-02
  2.10545055e-04 1.13280184e-04 1.35329389e-03 6.34899698e-05
  9.40059399e-05 1.09580476e-04 7.33662964e-05 6.42704181e-05
  4.54251931e-05 2.26399570e-04 1.95542634e-05 3.75881245e-05
  5.91732605e-05 3.86856089e-04 1.67657810e-04 5.48961048e-04
  2.37298105e-03 1.61499396e-04 3.55662451e-05 2.07612131e-04
  1.55795773e-03 6.29073940e-03 1.37697789e-04 7.65821722e-04
  1.08311884e-04 7.90575810e-04 6.64009131e-04 8.88707655e-06
  3.51798553e-05 1.47955172e-04 1.61534281e-05 3.98373784e-04
  7.23886333e-05 4.11021261e-04 9.88336687e-05 9.67652304e-05
  2.03252475e-05 5.41698886e-04 1.15518953e-04 2.18968344e-04
  8.04252268e-05 2.45380419e-04 2.16114509e-04 8.68377901e-05
  4.50017920e-04 3.65456520e-03 1.10031024e-05 2.31366430e-05
  1.74068240e-03 4.71293461e-05 7.42958509e-05 3.35850236e-05
  1.29288572e-04 1.17647709e-04 4.22777921e-05 1.38040501e-04
  1.40400458e-04 1.33142885e-05 3.48939851e-04 4.43727570e-03
  1.16582087e-04 3.31243646e-04 2.64177739e-04 2.55858595e-05
  8.24222388e-06 2.92424647e-05 1.27920212e-05 1.50949170e-04
  9.73921444e-04 2.34049967e-05 2.34747185e-05 7.87734753e-05
  1.00163044e-04 1.00137448e-04 1.30430024e-04 2.04405282e-04
  6.73659670e-05 1.49664585e-04 1.74392160e-04 1.30447937e-04
  1.40852408e-05 3.08184233e-03 9.25796339e-04 1.39377284e-04
  1.30143820e-03 5.90574928e-04 5.74775331e-05 1.35811046e-04
  7.28201048e-05 5.90168114e-04 5.79664920e-05 8.52270095e-05
  6.80576544e-04 1.71669142e-03 1.12484959e-04 5.05137796e-05
  2.60357137e-05 4.94460364e-05 1.53268593e-05 1.85246419e-04
  8.89942530e-05 1.93314074e-04 6.01026659e-05 1.10615802e-04
  8.32345086e-06 2.95822283e-05 1.87501940e-03 1.89307666e-05
  1.31245572e-02 4.41835327e-05 1.94803521e-04 1.19015771e-04
  3.75907955e-04 7.10801978e-05 1.68837374e-04 4.38386487e-05
  3.97459371e-05 1.18586831e-04 1.61943655e-03 1.13543938e-03
  1.05494983e-03 5.85651956e-03 8.51290388e-05 3.84870073e-04
  2.86146213e-04 4.66286510e-05 9.33238989e-05 1.77192676e-04
  3.38811660e-04 9.71617003e-04 8.85728077e-05 4.20117176e-05
  1.25351959e-04 1.16989890e-04 8.59961438e-06 2.81955174e-04
  7.44227800e-05 2.30974238e-05 1.43806246e-04 6.86498752e-05
  6.45910113e-05 1.37659386e-04 1.25927196e-04 2.99155538e-04
  1.27140611e-05 1.59415304e-05 6.95295530e-05 1.73781780e-04
  1.46330480e-04 7.44170711e-06 1.03268421e-05 2.91458000e-05
  1.42381643e-04 3.33269971e-04 7.69355218e-04 1.99857037e-04
  1.35441122e-04 9.49479363e-05 1.00538768e-04 8.30673089e-05
  8.03812509e-05 2.98772496e-03 2.77627696e-04 1.35924362e-04
  1.39287394e-03 1.52346067e-04 5.31824408e-05 5.44412142e-05
  2.48067547e-04 9.17954676e-05 4.91166757e-05 2.28250981e-04
  5.45849616e-04 3.89625020e-05 1.47091202e-03 1.12843503e-04
  3.10022951e-05 4.93905900e-05 1.27479710e-04 1.66557529e-05
  1.12638249e-04 1.57129369e-04 1.05814848e-04 7.73259962e-05
  1.39794472e-04 1.73086610e-05 1.45764730e-04 5.76937709e-05
  8.79273721e-05 1.24989776e-04 1.92956664e-04 3.16391117e-04
  1.22398502e-04 5.90232848e-05 2.20755173e-05 2.09033315e-05
  8.79537110e-05 7.22956393e-05 5.28881792e-05 1.57437607e-05
  1.40244476e-04 1.17487660e-04 5.43703150e-04 1.39969095e-04
  1.43344741e-05 1.83411466e-04 7.01302997e-05 5.52579222e-05
  2.88880314e-04 1.04400606e-04 1.18846492e-05 1.35885814e-04
  3.79063335e-04 3.91672773e-04 3.26941808e-05 2.69887951e-05
  6.15370009e-05 1.77064037e-04 3.63231957e-04 1.05110165e-02
  7.32653355e-03 1.77500409e-03 2.84675299e-03 1.86621547e-02
  3.37780730e-05 1.40097225e-04 9.41174876e-05 9.75245421e-05
  7.29837746e-04 1.06199585e-01 1.33491645e-03 2.18456800e-04
  1.47253726e-04 4.16491763e-04 2.31201132e-03 2.38496345e-04
  7.73552456e-05 3.60980048e-04 6.67347122e-05 9.55001669e-05
  1.41858269e-04 2.06856188e-04 3.82324302e-04 1.63317265e-04
  9.49466694e-03 1.27431820e-04 5.04222640e-04 8.87295537e-05
  3.58599646e-05 3.45981280e-05 2.41121652e-05 1.61980337e-04
  1.42218641e-05 1.38701027e-04 2.54837156e-04 2.14969448e-04
  4.36862744e-03 9.73729620e-05 1.15959963e-03 8.88847164e-04
  1.28892774e-03 1.92077961e-04 5.45617986e-05 1.12572743e-04
  1.59986354e-02 7.49700936e-04 4.81046690e-03 4.32648836e-03
  2.09037516e-05 3.92925904e-05 3.72121576e-05 3.55532742e-04
  7.65382501e-05 4.35747643e-05 2.03072195e-04 1.80994475e-03
  2.20806891e-04 9.50019166e-05 4.62464413e-05 3.93410737e-04
  1.42946476e-04 1.50018841e-05 2.83505287e-05 1.91206008e-03
  3.79732483e-05 4.25073849e-05 3.74040392e-05 1.57043381e-04
  2.07035875e-04 7.11141402e-05 8.35680912e-05 2.38825116e-04
  1.36987161e-04 1.14341313e-03 1.31729917e-04 3.34889453e-04
  3.31851217e-04 1.29217326e-04 1.70335716e-05 1.27158118e-02
  9.19590457e-05 1.48216641e-05 1.35478855e-03 4.57617082e-03
  1.24107741e-04 8.93392507e-03 3.09563096e-04 8.74133912e-05
  6.23598055e-04 5.44636241e-05 2.36913585e-03 4.86806326e-04
  1.49991305e-04 3.64911743e-04 7.65966903e-03 1.37028721e-04
  5.36098378e-04 9.98151395e-03 2.96420272e-04 5.01985560e-05
  3.55951197e-05 8.96760845e-04 1.02922975e-04 3.41462321e-04
  3.87956861e-05 1.74221102e-04 2.19501182e-03 2.10608905e-05
  2.86171708e-05 3.37320998e-05 9.73911199e-04 8.74081743e-05
  9.08347065e-05 5.98089478e-04 1.90035731e-04 2.48140896e-05
  3.22310771e-05 1.39478261e-05 7.46861770e-06 1.88128115e-03
  1.55279049e-04 7.93744584e-06 4.98286900e-05 5.41836838e-04
  7.59426621e-05 5.58087137e-04 2.57718293e-05 1.85724930e-05
  3.89003872e-05 1.36972332e-04 1.79691397e-05 2.75747763e-04
  3.59752122e-03 1.13748552e-04 2.28052770e-04 3.75784111e-05
  2.66920513e-04 4.21910299e-05 1.43733720e-04 1.28969741e-05
  5.30369016e-06 2.01334176e-03 2.63906913e-05 4.13805865e-05
  1.43911748e-04 6.67866043e-05 5.38090862e-05 2.59012868e-05
  1.09383975e-04 5.36186271e-05 1.98825892e-05 1.27018095e-04
  3.30074981e-05 3.29915420e-05 5.44356590e-04 1.60242300e-04
  8.68006900e-05 2.30927661e-04 3.19647297e-05 7.63655589e-06
  3.79793710e-05 3.10684321e-04 1.03531267e-04 6.78348733e-05
  4.17819720e-05 2.25741678e-04 6.87641150e-05 1.35805551e-03
  3.75074451e-05 2.10253100e-04 5.24306306e-05 2.14072468e-04
  6.75154384e-04 1.70973275e-04 1.76807473e-04 9.90701956e-05
  8.33111044e-05 2.45550691e-05 2.90844619e-05 4.72426153e-04
  8.43053276e-05 2.93365272e-04 1.08159009e-04 4.96202789e-04
  1.55976843e-04 3.45537293e-04 2.69339489e-05 1.64527795e-04]]